---
# HACK! I don't like using the AUR on a server
- name: Install build requirements
  pacman: name=binutils,mercurial,automake,autoconf,gcc,make state=installed

- name: Create build folder
  file: path=/tmp/build state=directory

- name: Download dovecot-antispam
  get_url: url=https://aur.archlinux.org/packages/do/dovecot2-antispam-hg/dovecot2-antispam-hg.tar.gz dest=/tmp/build/ force=yes

- name: Extract dovecot-antispam
  command: chdir=/tmp/build /bin/tar xzf dovecot2-antispam-hg.tar.gz

- name: Build dovecot-antispam
  command: chdir=/tmp/build/dovecot2-antispam-hg makepkg --asroot

- name: Install dovecot-antispam
  shell: pacman -U --noconfirm /tmp/build/dovecot2-antispam-hg/dovecot2-antispam-hg*.pkg.tar.xz

- name: Clean up the dovecot-antispam build folder
  file: path=/tmp/build state=absent
# HACK END
