---
- name: Install required packages
  pacman: name=sudo,postgresql,python2-psycopg2,postfix,dovecot,pigeonhole,clucene,opendkim,dspam,postgrey state=installed update_cache=yes

- include: ../../common/tasks/install_from_aur_build_local.yml package=dovecot2-antispam-hg

- include: configure_ssl.yml
- include: configure_cron.yml
- include: configure_postgresql.yml
- include: configure_dspam.yml
- include: configure_opendkim.yml
- include: configure_postgrey.yml
- include: configure_dovecot.yml
- include: configure_postfix.yml
